CREATE TABLE User
(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(256) NOT NULL,
Email VARCHAR(256) NOT NULL,
AccountCreated DATETIME NOT NULL
);

CREATE TABLE Resources 
(ResourceID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
ResourceName VARCHAR(256), 
ResourceType VARCHAR(256) NOT NULL CHECK(ResourceType IN ('Space','Equipment')), 
Location VARCHAR(256) NOT NULL CHECK(Location IN ('Wilson','Brodie'))
);

CREATE TABLE ClassSchedule
(ClassID       INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 ClassDay      VARCHAR(256) NOT NULL, 
 ClassTime     TIME NOT NULL, 
 ClassLocation VARCHAR(256) NOT NULL, 
 EnrollmentCap INTEGER
);

CREATE TABLE Bookings
(BookingID    INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 UserID       INTEGER NOT NULL, 
 DateBookedOn DATE NOT NULL, 
 TimeBookedAt TIME NOT NULL, 
 ResourceID   INTEGER NOT NULL, 
 ResourceType VARCHAR(256) NOT NULL,
 FOREIGN KEY (UserID) REFERENCES User(ID)
);

ALTER TABLE Bookings
ADD FOREIGN KEY ResourceID REFERENCES Resources(ResourceID);

ALTER TABLE Bookings
ADD FOREIGN KEY ResourceType REFERENCES Resources(ResourceType);


CREATE TABLE Enrollments
(ClassID   INTEGER NOT NULL, 
 UserID    INTEGER NOT NULL, 
 ClassDate INTEGER NOT NULL,
 PRIMARY KEY(ClassID, UserID, ClassDate), 
 FOREIGN KEY(ClassID) REFERENCES ClassSchedule(ClassID)
);

ALTER TABLE Enrollments
ADD FOREIGN KEY (UserID) REFERENCES User(ID);
